name: pasantapp
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.0-218.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.2
  google_nav_bar: ^5.0.6
  http: ^1.1.0
  provider: ^6.0.5
  salomon_bottom_bar: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0


flutter:

  
  uses-material-design: true

  assets:
    - assets/images/estudiantesBtn.webp
    - assets/images/organizacionBtn.webp
    - assets/images/cargando.gif
    - assets/images/startApp.jpg
    - assets/images/workSign.png
    
